name: CD - Deploy Backend Services to AKS

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        run: |
          az aks get-credentials \
            --name sit722-task8p-cluster \
            --resource-group sit722-task8p-rg \
            --overwrite-existing

      # 👇 Removed Attach ACR step (because we manually added role assignment)

      - name: Deploy ConfigMaps and Secrets
        run: |
          kubectl apply -f week08/k8s/configmaps.yaml
          kubectl apply -f week08/k8s/secrets.yaml

      - name: Deploy Databases
        run: |
          kubectl apply -f week08/k8s/product-db.yaml
          kubectl apply -f week08/k8s/order-db.yaml

      - name: Deploy Backend Services
        run: |
          kubectl apply -f week08/k8s/product-service.yaml
          kubectl apply -f week08/k8s/order-service.yaml

      - name: Verify Deployment
        run: |
          kubectl get pods -o wide
          kubectl get svc -o wide
