name: CD - Deploy Backend Services to AKS

on:
  workflow_dispatch:

jobs:
  deploy_backend:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - run: az aks get-credentials --resource-group sit722-task8p-rg --name sit722-task8p-cluster --overwrite-existing
      - run: az aks update --name sit722-task8p-cluster --resource-group sit722-task8p-rg --attach-acr sit722task8pacr

      - run: |
          cd k8s/
          kubectl apply -f configmaps.yaml
          kubectl apply -f secrets.yaml
          kubectl apply -f product-db.yaml
          kubectl apply -f order-db.yaml
          kubectl apply -f product-service.yaml
          kubectl apply -f order-service.yaml

      - run: az logout
