name: CD - Deploy Frontend to AKS

on:
  workflow_dispatch:
    inputs:
      product_api_ip:
        description: 'External IP of Product Service'
        required: true
        default: 'http://<product-ip>:8000'
      order_api_ip:
        description: 'External IP of Order Service'
        required: true
        default: 'http://<order-ip>:8001'

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - run: az aks get-credentials --resource-group sit722-task8p-rg --name sit722-task8p-cluster --overwrite-existing

      - run: az acr login --name sit722task8pacr

      - name: Inject Backend IPs into Frontend
        run: |
          sed -i "s|_PRODUCT_API_URL_|${{ github.event.inputs.product_api_ip }}|g" frontend/main.js
          sed -i "s|_ORDER_API_URL_|${{ github.event.inputs.order_api_ip }}|g" frontend/main.js
          cat frontend/main.js

      - name: Build and Push Frontend
        run: |
          docker build -t sit722task8pacr.azurecr.io/frontend:latest ./frontend/
          docker push sit722task8pacr.azurecr.io/frontend:latest

      - run: |
          cd k8s/
          kubectl apply -f frontend.yaml

      - run: az logout
