name: Frontend CI - Build & Push Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend_ci.yml'

env:
  ACR_LOGIN_SERVER: sit722task8pacr.azurecr.io
  IMAGE_TAG: ${{ github.sha }}-${{ github.run_id }}

jobs:
  build_and_push_frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - run: az acr login --name sit722task8pacr

      - name: Build and Push Frontend Image
        run: |
          docker build -t sit722task8pacr.azurecr.io/frontend:latest ./frontend/
          docker push sit722task8pacr.azurecr.io/frontend:latest

      - run: az logout
        if: always()
